### ISSUE TITLE
Assemble potentially contaminated isolates by default

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#100]
We recently implemented `--ignore_contamination_screen`, but I have noticed that I generally use this a lot, so maybe it would make sense to invert the logic here, so we have something like `--stop_on_contamination` instead, so isolates with potential contamination are not processed further. What do you think @thorellk @huyue87 ?

**Comment by thorellk** [comment]
This is implemented as a default in v 3.0
