### ISSUE TITLE
Add sendsketch taxonomic screening

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#113]

**Comment by boulund** [comment]
I guess we can consider this issue handled now, right @emilio-r ?  If we've merged your branch to the main branch now it should be done. Please close this if that is true.

**Comment by emilio-r** [comment]
This sort of already exist in the 3.E version/branch in the form of gramstain, but the issue will be handled via #117 if we expand the taxonomic output of that process. I'll close this issue.

**Comment by thorellk** [comment]
Done with v3.0
