### ISSUE TITLE
Known issues - 3.E

### ISSUE THREAD

**Issue by emilio-r** [ctmrbio/BACTpipe#116]
- Issues running pipe locally - Fixed
While some users report being able to run the pipe using the local configuration, most users get stuck on the shovill process which is also possibly resulting in different errors for different users.

- Rackham: sendsketch_stainer.py command not found.
Running the Rackham compatible branch on the cluster results in the process "screen for contaminants" failing due to not recognizing files in /bin directory via the error: .command.sh: line 4: sendsketch_stainer.py: command not found.

- Rackham: Assembly failed - spades.fasta has zero contigs!
Running the pipe in a conda evironment on Rackham results in shovill complaining of empty files. This is despite fastP producing a seemingly normal output.

- Sendsketch skipping
Some input read files, when run on the Rackham compatible version, skips the sendsketch process, this often by complaining that it cannot handle empty files. These contigs, from shovill, are simultaneously being fed correctly into the other processes (prokka and statswrapper). This issue always seem to affect the same read samples, despite these being able to function correctly in sendsketch, when done outside of the pipe.

- MultiQC
The MultiQC process does not produce the expected output.

**Comment by boulund** [comment]
Great that you summarized everything in here @emilio-r ! 

If you create a new issue for each of the issues listed above that are still relevant (i.e. not the fixed ones) it'll be easier to track the progress. You can refer to this issue in each and when individual issues have been created we will close this summary issue.

**Comment by abhi18av** [comment]
Regarding this issue, I think that these should still stand for [my PR here](https://github.com/ctmrbio/BACTpipe/pull/124) as I didn't alter any functionality. But still, it'd be great if we could test with the latest version? 

Also, please do note the `git revision` for the branch you pick for testing.

**Comment by thorellk** [comment]
I think we can close this issue since the items are either solved or covered by other issues. Do you agree @emilio-r ?
