### ISSUE TITLE
Improve sendsketch_stainer.py script

### ISSUE THREAD

**Issue by thorellk** [ctmrbio/BACTpipe#117]
I am thinking that we ideally could improve the stainer script to also output species (which would be useful to input to prokka). And if the sample is contaminated it could output "multiple species" or similar.

**Comment by thorellk** [comment]
Ideally it could also output the "strain" prefix into prokka. This would solve the issue with MultiQC.

**Comment by boulund** [comment]
Good ideas. Anyone interested in taking this on, @emilio-r or @thorellk ?

**Comment by emilio-r** [comment]
The script has been updated with the requested features and any changes to it now belongs to #133.
