### ISSUE TITLE
Rackham: Assembly failed - spades.fasta has zero contigs!

### ISSUE THREAD

**Issue by emilio-r** [ctmrbio/BACTpipe#119]
#116 
Running the pipe in a conda evironment on Rackham results in shovill complaining of empty files. This is despite fastP producing a seemingly normal output.

**Comment by thorellk** [comment]
Running the pipeline using the local.config file on Rackham without the bactpipe_env environment loaded does not generate this error but Shovill runs without problems so maybe we should do like that instead and change the instructions for installation accordingly.
