### ISSUE TITLE
Sendsketch skipping

### ISSUE THREAD

**Issue by emilio-r** [ctmrbio/BACTpipe#120]
#116 
Some input read files, when run on the Rackham compatible version, skips the sendsketch process, this often by complaining that it cannot handle empty files. These contigs, from shovill, are simultaneously being fed correctly into the other processes (prokka and statswrapper). This issue always seem to affect the same read samples, despite these being able to function correctly in sendsketch, when done outside of the pipe.

**Comment by thorellk** [comment]
This may have to do with shovill fasta header formats in some way. We should consider cleaning up fasta headers of the shovill output to something like >strain_contigX prior to feeding it into sendsketch and prokka respectively.

**Comment by thorellk** [comment]
This seems to have been solved by integrating the contig header renaming script.
