### ISSUE TITLE
MultiQC Issue

### ISSUE THREAD

**Issue by emilio-r** [ctmrbio/BACTpipe#121]
#116 
The MultiQC process does not produce the expected output.

**Comment by thorellk** [comment]
This is since the prokka result log files don't include unique strain identifiers. If we resolve issue #117 this problem will be resolved as well.

**Comment by emilio-r** [comment]
Issue fixed, but will be refined with the closure of #117. Since this issue is only relating to 3.E branch and the MultiQC now works there, I'm closing it.
