### ISSUE TITLE
Evaluate time and CPU usage on rackham

### ISSUE THREAD

**Issue by thorellk** [ctmrbio/BACTpipe#123]
So that we are not asking for too much allocation for the different processes (increases queuing time)

**Comment by thorellk** [comment]
@emilio-r and @boulund, do you have any input on this? Should we make another evaluation of resource usage based on the jobstats or should we leave it for now?

**Comment by emilio-r** [comment]
I think that any needed tweaks in the current set-up will become apparent once we start running it on our new data. Perhaps we should first see if we need to tweak the values, based on how the pipe handles that?

**Comment by thorellk** [comment]
Ok, let's close it for now and see if we have a reason to optimise it at a later timepoint.
