### ISSUE TITLE
Joint Zoom meeting to discuss next steps?

### ISSUE THREAD

**Issue by thorellk** [ctmrbio/BACTpipe#125]
Hi!

What about having a Zoom meeting together to introduce ourselves and discuss next steps forward + future vision for the pipeline and division of the work? When would suit you @boulund @emilio-r @abhi18av?

Best wishes,
Kaisa

**Comment by boulund** [comment]
Pretty much any time tomorrow works for me

**Comment by abhi18av** [comment]
Good idea!

Anytime between 9:30 CET and 3:30 CET works for me :)

**Comment by emilio-r** [comment]
Anytime today would work for me.

**Comment by thorellk** [comment]
Ok, what about in half an hour? 10.30 CET? @emilio-r @boulund @abhi18av? 
https://gu-se.zoom.us/j/64089983741?pwd=NU9XeWx0L293UDdyZHQ3MWhhVG1Ddz09

**Comment by boulund** [comment]
Please note that this Github is public so that link is now also public
