### ISSUE TITLE
emilio branch sendsketch_to_prokka.py gives incorrect output

### ISSUE THREAD

**Issue by thorellk** [ctmrbio/BACTpipe#128]
When running it on ~50 genomes I noted some of them did not get the genus and species classification that it should have gotten based on the sendsketch top hits, see attached files
[Species_prokka.txt](https://github.com/ctmrbio/BACTpipe/files/5666293/Species_prokka.txt)
[Top_sendsketch_hits.txt](https://github.com/ctmrbio/BACTpipe/files/5666294/Top_sendsketch_hits.txt)

**Comment by abhi18av** [comment]
@thorellk this is something perplexing for me as well. We are now using the same `sendsketch` script as the `3E` branch but it's misbehaving for some reason. 

Anyways, @emilio-r  could you please help identify which genomes are not being processed correctly and compare the behavior of `3E` and `emilio` branch to pin-point the exact issue?

I'll setup the `signalp` locally to fix this behavior.

**Comment by thorellk** [comment]
Yeah, it is really weird. I am running the same samples with the 3.E branch now to see if that gives the same error

**Comment by thorellk** [comment]
The 3.E branch does not output the genus or species at all

**Comment by abhi18av** [comment]
Hmm, so just to be clear `emilio` branch is in the right direction correct?

**Comment by thorellk** [comment]
The emilio branch runs without errors and outputs the genus and species info as it should (at least at a first glance). However, some of the genus and species that are fed into prokka are incorrect and don't agree with the top hits from sendsketch for those samples...

**Comment by abhi18av** [comment]
Hi @thorellk - Is there a way to check the `sendsketch` scripts independently on the data produced? 

I think that we should make sure that the `sendsketch.sh` and `sendsketch_to_prokka.py` are working as expected, something akin to unit testing these files.
CC @emilio-r

**Comment by thorellk** [comment]
I have now ran the python script separately and that gives correct output so it has do have something to do with the nextflow piping...

**Comment by thorellk** [comment]
Actually, it seems to be nextflow mixing things up. All the taxa that are incorrect are present as the top hit in one of the sendsketch files from another of the strains that got incorrect taxa. 

In the file below I have extracted the top three hits from the sendsketch output files. The things marked in green are the results of the manual sendsketch_to_prokka.py run (which are all correct). I also added the classification that has been sent into prokka and marked in red when there is a mismatch between the sendsketch results and the results input to prokka.

[Sendsketch2prokka_evaluation.xlsx](https://github.com/ctmrbio/BACTpipe/files/5671402/Sendsketch2prokka_evaluation.xlsx)

**Comment by abhi18av** [comment]
Aaand the plot thinkens 🤔 

The formatted excel file is extremely helpful @thorellk  - thanks!

Let me have a look and try to figure out where exactly is the issue within the nextflow process.

**Comment by thorellk** [comment]
Yeah, it seems like when it is executed on the HPC cluster, i.e. many processes are run in parallel, there is some confusion of the channels?

**Comment by abhi18av** [comment]
That could be another suspect (this might be a bug in NF), but my most immediate suspects are related to the pipeline design.

1. The mixup could be in the parameter code used to prepare arguments for `prokka` 

```nextflow


    prokka_reference_argument = ""
    if (params.prokka_reference) {
        prokka_reference_argument = "--proteins ${params.prokka_reference}"
    }

    prokka_gramstain_argument = ""

    if (stain == "pos") {
        prokka_gramstain_argument = "--gram pos"
    } else if (stain == "neg") {
        prokka_gramstain_argument = "--gram neg"
    } else {
        prokka_gramstain_argument = ""
    }

    prokka_genus_argument = ""
    prokka_species_argument = ""

    if (genus != "Multiple") {
        prokka_genus_argument = "--genus ${genus}"
        prokka_species_argument = "--species ${species}"
    } else {
        prokka_genus_argument = "--genus Multiple_taxa"
    }


```


The values are then passed to the actuall script

```
    prokka \
        --force \
        --evalue ${params.prokka_evalue} \
        --kingdom ${params.prokka_kingdom} \
        --locustag ${pair_id} \
        --outdir ${pair_id}_prokka \
        --prefix ${pair_id} \
        --strain ${pair_id} \
        ${prokka_reference_argument} \
        ${prokka_gramstain_argument} \
        ${prokka_genus_argument} \
        ${prokka_species_argument} \
        --compliant \
        ${contigs_file}

```

2. The other option is, I think more likely, that the mix-up happens in the two linkages to `prokka`. Initially, I suggested that we remove the link between `SHOVILL` and `PROKKA` since the `SCREEN_FOR...` already gets the `contig` file from `SHOVILL` and we can forward it from `SCREEN_FOR...` along with the `contamination profile`.

It's a known limitation of Nextflow that as of now we can't provide optional input, only optional output.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/12799326/101761439-27e19280-3b02-11eb-82c4-e34fb6f3e4ae.png">

**Comment by abhi18av** [comment]
In the meantime, till we confirm the logic of point-1 above, I've implemented point-2 here https://github.com/ctmrbio/BACTpipe/tree/use-screened-contig

**Comment by emilio-r** [comment]
@abhi18av Based on a smaller test sample this new version (use_screened_contig) seems to work and passes the arguments as it should. So, @thorellk, try running this branch and see if you get the same results using your more complex samples.

**Comment by thorellk** [comment]
I am testing the new branch now.

**Comment by thorellk** [comment]
Sorry for the delay, I had to be in the lab most of the day today.

Seems like the use_screened_contigs did the trick except that 5 out of 48 samples fails in the sendsketch step and thus does not get fed into prokka. Might be related to issue #120 and may be avoided by including the renaming script?

**Comment by abhi18av** [comment]
No worries @thorellk. I'll be giving `BACTpipe` some time over the weekend. 

Here's what I'm planning to do

1. Enable this pipeline to run on tower.nf , so that I can test this at scale as well.


2. Integrate the script you mentioned https://github.com/ctmrbio/BACTpipe/issues/129 


Could you please share the ids of the genomes which fail, along with 5 genomes which pass. Having a sample set of 10 should be enough for testing.

**Comment by thorellk** [comment]
Hi @abhi18av. I am sorry, I did not see your question on sharing data with you. My theory is that this is mainly and issue when running the pipeline on the HPC when many processes are ran in parallel. But if you want to see if you can replicate the issue locally, the data can be found here https://www.dropbox.com/sh/hu77ya6enz19w61/AAC6W2ez1y-KHPm--nIbYcKVa?dl=0

The it62* and CCUG-7* samples failed last time and the rest passed.

**Comment by abhi18av** [comment]
Hi @thorellk, apologies for the late response on this, I'm on the move at the moment with less than nice connectivity :( 

I did manage to make progress in containarizing and making BACTpipe runnable on other infrastructures (https://github.com/ctmrbio/BACTpipe/issues/126). With the data you've shared, I should be able to debug more effectively.

**Comment by thorellk** [comment]
@abhi18av, no worries, I hope you will settle soon! Let me know if there is anything I/we can help out with in the meantime.

**Comment by abhi18av** [comment]
@thorellk @boulund, I need a bit of help - whenever you're available next (perhaps Jan 2021) - could you please help me obtain a copy of `signalP version-5`? 

NOTE: This is not a blocker for me as of now, I've added a `prokka_gram` option to skip the usage of `singalP` for local testing.

I think it requires an academic email and I only have a personal and commercial email.

Here's what you might need to do 

1. Go to https://services.healthtech.dtu.dk/software.php
2. Select `SignalP`
3. You'll see something similar to the following

<img width="849" alt="image" src="https://user-images.githubusercontent.com/12799326/103007868-efcf4c00-4512-11eb-95bd-713b32f561ca.png">

I'm not sure how the process would go next.

**Comment by abhi18av** [comment]
With the `prokka_gram` set to `false`, all samples go through nicely. 

```
nextflow run https://github.com/ctmrbio/BACTpipe -r use-screened-contig --reads 'bactpipe_full_test/*_{R1,R2}.fastq.gz'  --prokka_gram false
```

<img width="911" alt="image" src="https://user-images.githubusercontent.com/12799326/103019291-59585600-4525-11eb-9fe5-10c533c973e1.png">


Once I have access to the `SignalP`, I'll continue debugging with the `prokka_gram = true` debugging.

**Comment by abhi18av** [comment]
Failure report with https://github.com/ctmrbio/BACTpipe/commit/b24e98d837ab9205b9c5031ad65145599551211d and while running with the (default) `prokka_gram = true`

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/12799326/103963107-435ab000-5137-11eb-8a0a-e2e272a1661c.png">

The following samples failed on the `SCREEN...` stage

<img width="993" alt="image" src="https://user-images.githubusercontent.com/12799326/103963407-f4614a80-5137-11eb-97fd-8f6655a010d8.png">

The visible contents of the one such directory
<img width="741" alt="image" src="https://user-images.githubusercontent.com/12799326/103963521-430ee480-5138-11eb-9f14-360e154b36ff.png">

And the logs and other files related to this directory, corresponding to `CCUG-33000` sample are attached here [5c.zip](https://github.com/ctmrbio/BACTpipe/files/5784719/5c.zip)

**Comment by abhi18av** [comment]
After the integration of the `rename_fasta.py` script https://github.com/ctmrbio/BACTpipe/issues/129 , I ran the pipeline again and it seems we are in good shape. 

<img width="977" alt="image" src="https://user-images.githubusercontent.com/12799326/103972546-ff25da80-514b-11eb-9e50-c1c0de9794c5.png">


@thorellk @emilio-r , please give it a go on the cluster and verify the results.

**Comment by thorellk** [comment]
I am running it on our cluster now. Will also make a test run locally on my laptop :)

**Comment by emilio-r** [comment]
I tried running the commit from your branch now, @abhi18av, but all of the SCREEN's are failing due to "python3: can't open file 'rename_fasta.py': [Errno 2] No such file or directory". Are you seeing this error as well @thorellk?

**Comment by thorellk** [comment]
@emilio-r, I am running from the newly merged 3.E branch and don't get that error (5 out of 65 have completed through prokka without error this far). However, I noted we need to omit the "--compliant" parameter in prokka to keep our new nice headers :)

**Comment by thorellk** [comment]
Wait, it looks like the renaming script output is not used as output of the `SCREEN_FOR_CONTAMINANTS `process, i.e not as input to prokka? Or am I interpreting it incorrectly @abhi18av? The output of the renaming script should be fed both "internally" into sendsketch and "externally" into the next process, i.e. `PROKKA`.

**Comment by abhi18av** [comment]
> I tried running the commit from your branch now ...

@emilio-r , sorry my bad - instead of that commit you could use the latest one. In that commit, the `rename_fasta.py` file wasn't elevated to an `executable` file so I made it an executable in a later commit. 

> Wait, it looks like the renaming script output is not used as output of the SCREEN_FOR_CONTAMINANTS process, i.e not as input to prokka?

@thorellk  Whoops, I didn't know that - I've simply used this only as an input to `sendsketch` here  https://github.com/ctmrbio/BACTpipe/blob/932d8d9a8229a66f55fe8c2a2efe6b83148d563d/modules/screen_for_contaminants/screen_for_contaminants.nf#L15

I have now implemented that here 559db521a0b067c236bac7b2805b7adf28bdd091 , could you please try with this commit?

**Comment by abhi18av** [comment]
> However, I noted we need to omit the "--compliant" parameter in prokka to keep our new nice headers :)

@thorellk, shall I remove the `--compliant` argument from the script here as well? 

https://github.com/ctmrbio/BACTpipe/blob/559db521a0b067c236bac7b2805b7adf28bdd091/modules/prokka/prokka.nf#L59

**Comment by thorellk** [comment]
No worries, @abhi18av, that misundertstanding is on me not being clear about it. I removed the --compliant parameter and will test run with the most recent version now :)

**Comment by thorellk** [comment]
Now I get the same error as @emilio-r ,` python3: can't open file 'rename_fasta.py': [Errno 2] No such file or directory` : I was running the `3.E 1b8625b`

**Comment by emilio-r** [comment]
I'm currently stuck in HPC queueing purgatory but after changing the call for the file to conform with the other calls:
`    rename_fasta.py \
        --input ${contigs_file} \
        --output ${pair_id}_contig.fa \
        --pre ${pair_id}_contig
`
I've now managed to pass 5/10 (so far this is 100%) and counting.

**Comment by abhi18av** [comment]
@emilio-r , perfect!

Yes, that is the issue which is now fixed with 85d0f17ca6242bbd930adc5656c7911f9b401d95

**Comment by thorellk** [comment]
I just ran through everything on 65 completely different genomes and it almost works perfectly. One issue is that several strains get "Null null" on genus and species even if the sendsketch output file looks ok. @emilio-r, have you noted anything similar? I will dig into this more in detail.

**Comment by thorellk** [comment]
I don't get it, when/why would it output genus "Null" and species "null"? None of the sendsketch output files looks weird and the same genomes have worked previously...

Seems like I cannot attach xml files so here is a Dropbox link to the multiQC output https://www.dropbox.com/s/8s08gwsp6mic3ub/multiqc_report.html?dl=0

**Comment by boulund** [comment]
Try to see if you can identify where in the processing chain the nulls appear. Is it from sendsketch, or before or after that?

**Comment by thorellk** [comment]
Seems like it happens when the genus is not in the list?

```
cat /proj/uppstore2017270/kaisas/misc_WGS/BACTpipe/work/b7/3bb92b06eccc55723c13987e7a8103/.command.log

nxf-scratch-dir s16:/scratch/3479899/nxf.lwdInRis3w
Parsing CCUG-68518.contigs.fa
Wrote 40 contigs to CCUG-68518_contig.fa.
Adding /crex/proj/uppstore2017270/kaisas/misc_WGS/BACTpipe/work/conda/env-3b12f71134feb842065aa76592fe3f68/opt/bbmap-38.87-0/resources/blacklist_refseq_merged.sketch to blacklist.
0.078 seconds.
Loaded 1 sketch in 0.202 seconds.
Total Time: 	3.856 seconds.
Not_in_list	Globicatella	sulfidifaciens
```

**Comment by emilio-r** [comment]
After finally having some results I can confirm that I am seeing the same issue as you @thorellk. However, while sendsketch seems to output correct values (from .command.out):
`Parsing 192_S54_L001.contigs.fa
Wrote 42 contigs to 192_S54_L001_contig.fa.
neg	Helicobacter	pylori
`
Prokka doesn't recieve this (from .command.sh of the same):
`#!/bin/bash -ue
prokka         --cpus 1         --force         --evalue 1e-09         --kingdom Bacteria         --locustag 192_S54_L001         --outdir 192_S54_L001_prokka         --prefix 192_S54_L001         --strain 192_S54_L001         --proteins /proj/uppstore2017270/Emilio/bactpipe-testing/Bactpipe-tests_indata/HP26695_for_annot_w_phage_T4SS_200318.faa                  --genus null         --species null         192_S54_L001_contig.fa
`
It also occurs to me that this particular sample has not been assigned any gramstain either.

**Comment by abhi18av** [comment]
Hmm, I think that there could be two reasons behind this 

1. **Less likely:** The logic behind the `sendsketch` which reads through the global `$projectDir/resources/gram_stain.txt` and handles the overall determination of the genus.

2. **More likely:** The `stdout` is a bit unreliable and we should instead rely on a small CSV file which is passed from `SCREEN...` to `PROKKA` process.

I'll tweak the code and update here once its ready for testing.

**Comment by abhi18av** [comment]
Hi team,

Apologies for the late update on this one, when I seemed to be done with the removal of `stdout` I keep running into the pesky python script issue and this is what's taking up my time before I ask for another run on the cluster.

```

0.009 seconds.
Loaded 1 sketch in 0.051 seconds.
Total Time:     1.055 seconds.
Traceback (most recent call last):
  File "/root/BACTpipe/bin/sendsketch_to_prokka.py", line 20, in <module>
    genus_two = genus_two_line.split("\t")[11].split(" ")[0]
IndexError: list index out of range
```

**Comment by boulund** [comment]
That looks an error that would pop up if you're trying to split an empty string. Could this line be the source of the nulls we've observed?
I would argue that particular Python code needs some improvements with regards to error handling, it can be written a bit more defensively to ensure no invalid outputs are spat out. Step one would be to investigate which strings cause the issue you observed @abhi18av , and then wrapping all such lines in try-except and handle cases gracefully.

**Comment by emilio-r** [comment]
@abhi18av, I just ran 5499716 on the HPC and I did not see this error. Instead all of my 10 test samples pass and are given the correct values from sendsketch to prokka, and produce the expected MultiQC.

**Comment by thorellk** [comment]
Ok, great @emilio-r, let's merge the branches as soon as you feel ready @abhi18av and then take it from there.

**Comment by abhi18av** [comment]
> Step one would be to investigate which strings cause the issue you observed @abhi18av , and then wrapping all such lines in try-except and handle such cases gracefully.

@boulund , interestingly @emilio-r  and I have seen this error pop up if there's a change in python version as well. This is counter intuitive as well but that's what we saw. What I'd really prefer is having a compiled binary or at least package and publish this script on conda - perhaps even on a non-bioconda channel (Gothenberg university, perhaps).

Let's add the enhacements of the python scripts to `v3.1` milestone.

@thorellk , I'm merging https://github.com/ctmrbio/BACTpipe/pull/131 into `3.E` branch and I guess, the next step is to update the `docs` accrodingly.

**Comment by abhi18av** [comment]
> @abhi18av, I just ran 5499716 on the HPC and I did not see this error. Instead all of my 10 test samples pass and are given the correct values from sendsketch to prokka, and produce the expected MultiQC.

Cool, then shall we consider [this current issue](https://github.com/ctmrbio/BACTpipe/issues/128) resolved?

**Comment by thorellk** [comment]
I'd say yes. It has been an issue involving quite wide-ranging aspects of the original error ;)

**Comment by abhi18av** [comment]
Hehe, true! This has undoubtedly been one of the longest issues I've participated on Github. Happy to be moving forward :)

**Comment by boulund** [comment]
> @boulund , interestingly @emilio-r and I have seen this error pop up if there's a change in python version as well. This is counter intuitive as well but that's what we saw. What I'd really prefer is having a compiled binary or at least package and publish this script on conda - perhaps even on a non-bioconda channel (Gothenberg university, perhaps).

That behavior is odd. I'd love to hear more about why you think that occurs. 

On the topic of putting the script elsewhere I'm actually not in favor of packaging and publishing this script in a separate system, that just adds more unnecessary steps and complexity to the inclusion of what is really just a very minor internal implementation detail in BACTpipe. It would make more sense to just keep around within the workflow as is, as any potential future updates of that script would still require updates to BACTpipe anyway. As soon as everything settles in BACTpipe I guess the only reason for making changes to that script would be updates to BBMap, which would require updating the pinned version in the conda envs/docker images for BACTpipe anyway.

**Comment by abhi18av** [comment]
@boulund, I agree it makes sense to keep the script close to the pipeline. We do need to figure out the reason why the `out of index error` pops up with different Python version.

Let's look into this when we address the error handling situation in the python script.
https://github.com/ctmrbio/BACTpipe/issues/133

**Comment by boulund** [comment]
Step one is to be able to reliably reproduce the error, we need to find input samples that behave the way you are describing. Then it should be straightforward to fix the error
