### ISSUE TITLE
Integrate renaming script pre sendsketch

### ISSUE THREAD

**Issue by thorellk** [ctmrbio/BACTpipe#129]
I would like to integrate a script renaming the headers of the assembly fasta files from shovill to short, standardized headers including the strain identifier so that they would look like

```
>strainX_contig1
>strainX_contig2
```

This would hopefully make them less error prone and also a more suitable as prokka output. This way we would not have to write out the shovill assembly output file and could only write the cleaned assembly file after the screen for contaminants process, which would also agree better with the new use-screened-contigs branch. The only problem is that the script that I have used prior to this is not written in python3, which I think it should be to minimize extra dependencies. Would any of you @abhi18av @emilio-r or @boulund be able to translate that to python3 for me? I called it a txt file since .py files could not be uploaded here

[rename_fasta.txt](https://github.com/ctmrbio/BACTpipe/files/5673424/rename_fasta.txt)

**Comment by abhi18av** [comment]
> This way we would not have to write out the shovill assembly output file and could only write the cleaned assembly file after the screen for contaminants process ...

@thorellk , I do like this idea overall. We can integrate this once we've sure of the current code.


Regarding the script , here's the python3 version. 

[rename_fasta.py.txt](https://github.com/ctmrbio/BACTpipe/files/5673587/rename_fasta.py.txt)


The only changes I've made to convert this script were to update the `print` statements, luckily the script is short :)
```python3
    print('Parsing {}'.format(args.input))
...

    print('Wrote {0} contigs to {1}.'.format(count, args.output))


```

Please let me know the if it works as expected.

**Comment by thorellk** [comment]
Works like a charm 👍

**Comment by abhi18av** [comment]
P.S. You could try out the `2to3` tool which comes bundled with `Python3` to make sure that there are not huge changes necessary for the upgrade.

**Comment by abhi18av** [comment]
@thorellk , just to confirm you would like this `rename_fasta.py` to be included in the `SCREEN_FOR_CONTAMINATION` process right? 

And this renaming should occuer before any of the other processes?

**Comment by abhi18av** [comment]
Am I correct in invoking the script like this 

```
python3 rename_fasta.py --input A-salmonicida.contigs.fa --output A-salmonicida.contigs.renamed.fa 

```

...this yields a runtime issue for me.

```
Parsing A-salmonicida.contigs.fa
Traceback (most recent call last):
  File "rename_fasta.py", line 44, in <module>
    main()
  File "rename_fasta.py", line 32, in main
    fasta_out.write(contig_id)
TypeError: a bytes-like object is required, not 'str'


```

**Comment by thorellk** [comment]
Hi @abhi18av!
Sorry for my delay in responding. Yes, I thought it could be good to have it as step one in the `SCREEN_FOR_CONTAMINATION` process since it hopefully may decrease the risk for sendsketch failing. The --pre pattern should be the same as `pair_id_'contig'`, would that be possible? For the example above it would be `A-salmonicida_contig`

**Comment by thorellk** [comment]
Hi @abhi18av! Now we are back from holidays :) Should we take a Skype/Zoom some day later in the week to catch up a bit?

**Comment by abhi18av** [comment]
Hi @thorellk! 

Sure, I’m available as well. Please let me know of a good time to connect.

**Comment by thorellk** [comment]
Hi! Either today (I am available for another 4 hours), Thursday afternoon or Friday any day would work for me. How about you?

**Comment by abhi18av** [comment]
@thorellk, today I have a few backlog tasks lined up for this week - if possible I do prefer Thursday :) 

Please feel free to mark the calendar and share the meeting link at abhi18av__at__outlook__dot__com

**Comment by thorellk** [comment]
Great, I sent an invite for a Zoom call Thursday 14.00 CET :)

**Comment by abhi18av** [comment]
Thanks! Looking forward to finalizing the pipeline soon 😊

**Comment by abhi18av** [comment]
With this commit 7a6d00fa72f6628ee3b52b6a74db89801ab94d1b, the renaming script has been integrated.
