### ISSUE TITLE
Decide on what files to output

### ISSUE THREAD

**Issue by thorellk** [ctmrbio/BACTpipe#132]
Currently the pipeline outputs a few more files than necessary. I'd suggest not to output the renamed `${pair_id}.contigs.fa` file on top of the shovill output folder. Also, there is no need to output the renamed `${pair_id}_contig.fa` file from the `SCREEN_FOR_CONTAMINANTS` process since an identical file will also be output in the `PROKKA` process.

**Comment by abhi18av** [comment]
I'm adding a breadcrumb for a future reference.

We can use the `pattern` option for the `publishDir` directive to limit the files which are published.

https://www.nextflow.io/docs/latest/process.html#publishdir

**Comment by thorellk** [comment]
Ok, I guess this is the only thing remaining to release v 3.0. What do you think @abhi18av @emilio-r @boulund? Does all the files above (plus the new .tsv file from SCREEN_FOR_CONTAMINANTS) really need to be written out or can they be removed as soon as they have been used by the next process?

**Comment by emilio-r** [comment]
My piece is that we should aim at taxing the user's storage as little as possible. For instance, right now we have at least four copies of the ${pair_id}_contig.fa file (two in results and two in the resp. work-directories). Depending on what species you are putting through the pipe, and how many genomes there are, this may have a big impact.
As these types of intermediate files have no real use for the user i suggest we remove them after use, as you suggest @thorellk.

**Comment by abhi18av** [comment]
Actually they are being written out because the publish strategy and stageIn/Out strategy is set to copy by default on the executors. Using the pattern option for publishDir, we can limit what gets published. Emilio, would you like to give this on a shot in the meantime?

I'd only be able to slice out time later in the evening due to a priority task at hand.

**Comment by boulund** [comment]
I see no reason to publish those files either. They are there in the work folder if anyone would want to troubleshoot things anyway. 

When we run nextflow pipelines locally we typically use the hardlink directive to reduce unnecessary space waste. Symlinks also works, but that creates a potential issue if users for some reason decide to delete the work dir not realizing it will delete all the output files (since they were only symlinked from the work dir). Hardlinks is usually not an option in a cluster environment however. Long story short, I think we should keep the copy strategy, but limit the amount of files copied to the publishDir :D

**Comment by thorellk** [comment]
Should we implement this before the 3.0 release? I read the info in the link you sent @abhi18av and agree on what @boulund wrote about keeping the copying strategy but I am not sure how to best apply it practically. Would you be able to give it a go? If so, I will update the docs to adhere to our latest changes in the meantime.

**Comment by abhi18av** [comment]
Hi @thorellk 👋 , 

Yes, I'm working on this on improving the file outputs here https://github.com/ctmrbio/BACTpipe/pull/135 

I'd just like to confirm the following status.


```nextflow

process ASSEMBLY_STATS {
    publishDir "${params.output_dir}/shovill", mode: 'copy'

    output:
    file("${pair_id}.assembly_stats.txt") ✅ 

}


process SHOVILL {
    publishDir "${params.output_dir}/shovill", mode: 'copy'

    output:
    tuple val(pair_id), path("${pair_id}.contigs.fa") 🟥 
    path("${pair_id}_shovill/*.{fasta,fastg,log,fa,gfa,changes,hist,tab}") ✅ 
}


process FASTP {
    publishDir "${params.output_dir}/fastp", mode: 'copy'

    output:
    tuple val(pair_id), path("${pair_id}_{1,2}.fastp.fq.gz"), emit: shovill_input ✅ 
    path "${pair_id}.json", emit: fastp_reports ✅ 
}


process MULTIQC {
    publishDir "${params.output_dir}/multiqc", mode: 'copy'

    output:
    path('multiqc_report.html') ✅ 
}


process PROKKA {
    publishDir "${params.output_dir}/prokka", mode: 'copy'

    output:
    path("${pair_id}_prokka") ✅ 
}


process SCREEN_FOR_CONTAMINANTS {
    publishDir "${params.output_dir}/sendsketch", mode: 'copy'

    output:
    path "${pair_id}_stain_genus_species.tsv" 🟥 
    tuple val(pair_id), path("${pair_id}_contig.fa") 🟥 
    path "${pair_id}.sendsketch.txt" ✅ 
}



```

**Comment by abhi18av** [comment]
Hmm, not really.

We could set the default for all process to publish, and add a parameter _per process_ to allow the user to specify whether to publish the results of that process at all or not.

The downside is that, we'd be increasing the total number of parameters 👀.

**Comment by thorellk** [comment]
What do you think @boulund and @emilio-r? I guess those two processes would be the only ones that would make a difference size-wise. At least the trimmed reads files can be quite large.

**Comment by boulund** [comment]
I think the opposite would make more sense actually: introduce flags such as e.g. `--keep-trimmed-fastq`, so the defaults can be to not keep them.

**Comment by thorellk** [comment]
Ok, then let's introduce the `--keep-trimmed-fastq`, and `--keep-shovill-output` to start with and see if someone asks for the other options as well?

**Comment by abhi18av** [comment]
@thorellk ,

I've added these parameters with this commit https://github.com/ctmrbio/BACTpipe/pull/135/commits/575aeb6362f1f455c6018326637c43430e2522aa 

However, one caveat of using stageIn/Out strategy set to copy by default on the executors is that the `SHOVILL` process still publishes `shovill` folder with `*_assembly_stats.txt` and correctly ignores the publication of `*_shovill` folder and `*.contig*` files.

I'd need to experiment further to understand how to overcome this. I do believe that this is not a hard blocker for anyone and we can still continue with the 3.0 release. What do you think?

**Comment by thorellk** [comment]
To output the stats file is fine, the shovill outputs are the heavy ones

**Comment by thorellk** [comment]
I just noted the fastp .json output file needs to be output as well since MultiQC is using that for statistics purposes. It also importantly needs to have the suffix *fastp.json and not only *json for MultiQC to recognize it

**Comment by abhi18av** [comment]
Okay, so with this commit https://github.com/ctmrbio/BACTpipe/pull/135/commits/215bd2640b3208805036910de7d3ae4bedd20c33 I've update 

- the name of the shovill output param to `keep_all_shovill_output` to better reflect the current situation
- the name of the `json` files generated by `fastp`

**Comment by abhi18av** [comment]
I think we should do the same for `fastp` as well and by default publish the `json` files - right now it won't publish anything.

 If you agree I could update the config param to `keep_all_fastp_output` to allow the user to get the `fastp` files as well. What do you think?

**Comment by abhi18av** [comment]
Whoops, my bad.


>  If you agree I could update the config param to `keep_all_fastp_output` to allow the user to get the `fastp` files as well. What do you think?

This wouldn't be possible since the `FASTP` process occurs at the beginning.

**Comment by thorellk** [comment]
The json and assembly stats files are both a kind of log/stats files that will tell the user about the quality of the data and the assembly results respectively so it would make quite a lot of sense to output them regardless. So I think `--keep-trimmed-fastq` and `--keep-shovill-output` (assemblystats is not a part of the shovill process or software itself) are still reasonable names for the parameters.

**Comment by thorellk** [comment]
(i.e. always output json file but not fastq files from fastp and default don't output shovill output folder but always output assemblystats file).

**Comment by abhi18av** [comment]
Oki doki, let me see how can we publish the minimal set of files by default.

**Comment by thorellk** [comment]
Great, the way I visualized it is documented in the output.rst file of the 3.E docs folder.

**Comment by abhi18av** [comment]
Here's how the pipeline results stand at 379bb408c1da6afe872228e8eaf0cb174300433c

1. **With** `--keep_trimmed_fastq` and `--keep_shovill_output` 

```
(base) Abhinavs-MacBook-Pro:u_ctmrbio_r_BACTpipe eklavya$ tree BACTpipe_results/
BACTpipe_results/
├── fastp
│   ├── A-salmonicida.fastp.json
│   ├── A-salmonicida_1.fastp.fq.gz
│   ├── A-salmonicida_2.fastp.fq.gz
│   ├── CCUG-26476.fastp.json
│   ├── CCUG-26476_1.fastp.fq.gz
│   ├── CCUG-26476_2.fastp.fq.gz
│   ├── CCUG-30872.fastp.json
│   ├── CCUG-30872_1.fastp.fq.gz
│   ├── CCUG-30872_2.fastp.fq.gz
│   ├── CCUG-33000.fastp.json
│   ├── CCUG-33000_1.fastp.fq.gz
│   ├── CCUG-33000_2.fastp.fq.gz
│   ├── CCUG-72405.fastp.json
│   ├── CCUG-72405_1.fastp.fq.gz
│   ├── CCUG-72405_2.fastp.fq.gz
│   ├── CCUG-74566.fastp.json
│   ├── CCUG-74566_1.fastp.fq.gz
│   ├── CCUG-74566_2.fastp.fq.gz
│   ├── CCUG-74904.fastp.json
│   ├── CCUG-74904_1.fastp.fq.gz
│   ├── CCUG-74904_2.fastp.fq.gz
│   ├── CCUG-74956.fastp.json
│   ├── CCUG-74956_1.fastp.fq.gz
│   ├── CCUG-74956_2.fastp.fq.gz
│   ├── H-Felis-CS1.fastp.json
│   ├── H-Felis-CS1_1.fastp.fq.gz
│   ├── H-Felis-CS1_2.fastp.fq.gz
│   ├── it162.fastp.json
│   ├── it162_1.fastp.fq.gz
│   └── it162_2.fastp.fq.gz
├── multiqc
│   └── multiqc_report.html
├── prokka
│   ├── A-salmonicida_prokka
│   ├── CCUG-26476_prokka
│   ├── CCUG-30872_prokka
│   ├── CCUG-33000_prokka
│   ├── CCUG-72405_prokka
│   ├── CCUG-74566_prokka
│   ├── CCUG-74904_prokka
│   ├── CCUG-74956_prokka
│   ├── H-Felis-CS1_prokka
│   └── it162_prokka
├── sendsketch
│   ├── A-salmonicida.sendsketch.txt
│   ├── CCUG-26476.sendsketch.txt
│   ├── CCUG-30872.sendsketch.txt
│   ├── CCUG-33000.sendsketch.txt
│   ├── CCUG-72405.sendsketch.txt
│   ├── CCUG-74566.sendsketch.txt
│   ├── CCUG-74904.sendsketch.txt
│   ├── CCUG-74956.sendsketch.txt
│   ├── H-Felis-CS1.sendsketch.txt
│   └── it162.sendsketch.txt
└── shovill
    ├── A-salmonicida.assembly_stats.txt
    ├── A-salmonicida_shovill
    │   ├── A-salmonicida.changes
    │   ├── A-salmonicida.fa
    │   ├── A-salmonicida.fasta
    │   ├── A-salmonicida.fastg
    │   ├── A-salmonicida.gfa
    │   ├── A-salmonicida.hist
    │   ├── A-salmonicida.log
    │   └── A-salmonicida.tab
    ├── CCUG-26476.assembly_stats.txt
    ├── CCUG-26476_shovill
    │   ├── CCUG-26476.changes
    │   ├── CCUG-26476.fa
    │   ├── CCUG-26476.fasta
    │   ├── CCUG-26476.fastg
    │   ├── CCUG-26476.gfa
    │   ├── CCUG-26476.hist
    │   ├── CCUG-26476.log
    │   └── CCUG-26476.tab
    ├── CCUG-30872.assembly_stats.txt
    ├── CCUG-30872_shovill
    │   ├── CCUG-30872.changes
    │   ├── CCUG-30872.fa
    │   ├── CCUG-30872.fasta
    │   ├── CCUG-30872.fastg
    │   ├── CCUG-30872.gfa
    │   ├── CCUG-30872.hist
    │   ├── CCUG-30872.log
    │   └── CCUG-30872.tab
    ├── CCUG-33000.assembly_stats.txt
    ├── CCUG-33000_shovill
    │   ├── CCUG-33000.changes
    │   ├── CCUG-33000.fa
    │   ├── CCUG-33000.fasta
    │   ├── CCUG-33000.fastg
    │   ├── CCUG-33000.gfa
    │   ├── CCUG-33000.hist
    │   ├── CCUG-33000.log
    │   └── CCUG-33000.tab
    ├── CCUG-72405.assembly_stats.txt
    ├── CCUG-72405_shovill
    │   ├── CCUG-72405.changes
    │   ├── CCUG-72405.fa
    │   ├── CCUG-72405.fasta
    │   ├── CCUG-72405.fastg
    │   ├── CCUG-72405.gfa
    │   ├── CCUG-72405.hist
    │   ├── CCUG-72405.log
    │   └── CCUG-72405.tab
    ├── CCUG-74566.assembly_stats.txt
    ├── CCUG-74566_shovill
    │   ├── CCUG-74566.changes
    │   ├── CCUG-74566.fa
    │   ├── CCUG-74566.fasta
    │   ├── CCUG-74566.fastg
    │   ├── CCUG-74566.gfa
    │   ├── CCUG-74566.hist
    │   ├── CCUG-74566.log
    │   └── CCUG-74566.tab
    ├── CCUG-74904.assembly_stats.txt
    ├── CCUG-74904_shovill
    │   ├── CCUG-74904.changes
    │   ├── CCUG-74904.fa
    │   ├── CCUG-74904.fasta
    │   ├── CCUG-74904.fastg
    │   ├── CCUG-74904.gfa
    │   ├── CCUG-74904.hist
    │   ├── CCUG-74904.log
    │   └── CCUG-74904.tab
    ├── CCUG-74956.assembly_stats.txt
    ├── CCUG-74956_shovill
    │   ├── CCUG-74956.changes
    │   ├── CCUG-74956.fa
    │   ├── CCUG-74956.fasta
    │   ├── CCUG-74956.fastg
    │   ├── CCUG-74956.gfa
    │   ├── CCUG-74956.hist
    │   ├── CCUG-74956.log
    │   └── CCUG-74956.tab
    ├── H-Felis-CS1.assembly_stats.txt
    ├── H-Felis-CS1_shovill
    │   ├── H-Felis-CS1.changes
    │   ├── H-Felis-CS1.fa
    │   ├── H-Felis-CS1.fasta
    │   ├── H-Felis-CS1.fastg
    │   ├── H-Felis-CS1.gfa
    │   ├── H-Felis-CS1.hist
    │   ├── H-Felis-CS1.log
    │   └── H-Felis-CS1.tab
    ├── it162.assembly_stats.txt
    └── it162_shovill
        ├── it162.changes
        ├── it162.fa
        ├── it162.fasta
        ├── it162.fastg
        ├── it162.gfa
        ├── it162.hist
        ├── it162.log
        └── it162.tab


```

2. **Without** these options i.e the default

```
BACTpipe_results/
├── fastp
│   ├── A-salmonicida.fastp.json
│   ├── CCUG-26476.fastp.json
│   ├── CCUG-30872.fastp.json
│   ├── CCUG-33000.fastp.json
│   ├── CCUG-72405.fastp.json
│   ├── CCUG-74566.fastp.json
│   ├── CCUG-74904.fastp.json
│   ├── CCUG-74956.fastp.json
│   ├── H-Felis-CS1.fastp.json
│   └── it162.fastp.json
├── multiqc
│   └── multiqc_report.html
├── prokka
│   ├── A-salmonicida_prokka
│   ├── CCUG-26476_prokka
│   ├── CCUG-30872_prokka
│   ├── CCUG-33000_prokka
│   ├── CCUG-72405_prokka
│   ├── CCUG-74566_prokka
│   ├── CCUG-74904_prokka
│   ├── CCUG-74956_prokka
│   ├── H-Felis-CS1_prokka
│   └── it162_prokka
├── sendsketch
│   ├── A-salmonicida.sendsketch.txt
│   ├── CCUG-26476.sendsketch.txt
│   ├── CCUG-30872.sendsketch.txt
│   ├── CCUG-33000.sendsketch.txt
│   ├── CCUG-72405.sendsketch.txt
│   ├── CCUG-74566.sendsketch.txt
│   ├── CCUG-74904.sendsketch.txt
│   ├── CCUG-74956.sendsketch.txt
│   ├── H-Felis-CS1.sendsketch.txt
│   └── it162.sendsketch.txt
└── shovill
    ├── A-salmonicida.assembly_stats.txt
    ├── CCUG-26476.assembly_stats.txt
    ├── CCUG-30872.assembly_stats.txt
    ├── CCUG-33000.assembly_stats.txt
    ├── CCUG-72405.assembly_stats.txt
    ├── CCUG-74566.assembly_stats.txt
    ├── CCUG-74904.assembly_stats.txt
    ├── CCUG-74956.assembly_stats.txt
    ├── H-Felis-CS1.assembly_stats.txt
    └── it162.assembly_stats.txt



```


With this feature added, based on our discussions - I'm now marking this issue as done:)
