### ISSUE TITLE
The documentation for 3.0 is not automatically updated by sphinx

### ISSUE THREAD

**Issue by thorellk** [ctmrbio/BACTpipe#138]
Maybe the config file is outdated? @boulund, or @abhi18av are any of you up to date with how to do this?

**Comment by abhi18av** [comment]
Unfortunately no, I'd need to read quite a bit for debuggin sphinx configs.

**Comment by thorellk** [comment]
Ok, @boulund did it last time so let's give him a chance to look at it first. I have never done it before and don't have any time to dig into it deeper until the end of next week...

**Comment by boulund** [comment]
I think you were just a bit impatient. I just looked at https://bactpipe.readthedocs.io/en/latest/ and it looks updated to me?

**Comment by thorellk** [comment]
Now it does, I guess it just took a while then :)
