### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#139]
The changelog does not include anything about the recent 3.0 release. It should be updated to highlight significant changes so users can easily see how the new release affects them.

**Comment by emilio-r** [comment]
I gave this a shot with the main changes. Anything that I am forgetting?

## [3.0.0] - 2021-01-15
### Added
- A script was implemented that renames the headers of fasta-files.
- New optional flags to improve lessen storage use:
	'--keep_trimmed_fastq' will allow output of trimmed reads (default = not saved)
	'--keep_shovill_output' will output the assemblies from shovill, in conjunction
	with assembled genomes from prokka (default = only from prokka)
- Contamination screen is now parsed and fed as taxonomic info for prokka.
- MultiQC now incorporates the trimmed QC reports as well.
- User now receives a file with compiled assemblystats, generated via BBmap's statswrapper. 

### Changed
- QC and trimming now done by FastP, not BBduk and FastQC, resulting in a much faster runtime.
- Contamination screening now done by Sendsketch.
- Contamination now ascertained from assemblies, not trimmed reads.
- BACTpipe now updated to DLS2-format.
- Updated required Nextflow version.

### Removed
- BBduk no longer used.
- FastQC no longer used.
- Mashscreen no longer used.

### Deprecated
