### ISSUE TITLE
Running with the latest stable nextflow version (20.10.0) does not work

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#146]
We should have mentioned in the documentation that running BACTpipe doesn't work with the latest stable release, as it relies on the new stub feature introduced in the latest edge release:

```
$ nextflow run ctmrbio/BACTpipe -profile rackham --profile bio --reads data/
*_R{1,2}.fastq.gz
N E X T F L O W  ~  version 20.10.0
Launching `ctmrbio/BACTpipe` [cheeky_sinoussi] - revision: 68cbd929c1 [master]
============================================================
BACTpipe
Version 3.0
Bacterial whole genome analysis pipeline
https://bactpipe.readthedocs.io
============================================================
Module compilation error
- file : /nfshome/home/boulund/.nextflow/assets/ctmrbio/BACTpipe/./modules/assembly_stats/assembly_stats.nf
- cause: Invalid process definition -- Unknown keyword `stub` @ line 20, column 5.
       """
       ^

1 error
```

Not very nice for new users to have to find that out for themselves.

Installing the latest edge release solves the issue, but it is not mentioned anywhere in the BACTpipe docs.

**Comment by thorellk** [comment]
Yes, this is stated on the front page but maybe we should put it in the installation section as well?

**Comment by boulund** [comment]
Yes, it's in the README, but not mentioned anywhere in the docs. I think it should be there as well, at least until it's a feature that is part of the stable releases.
