### ISSUE TITLE
The docs still makes references to database paths

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#147]
This section still mentions paths to reference databases: https://github.com/ctmrbio/BACTpipe/blob/master/docs/source/running.rst#changing-settings-on-the-command-line

I think that is no longer relevant.

**Comment by thorellk** [comment]
Do you mean the prokka reference path @boulund? This is a feature we use regularly.

**Comment by boulund** [comment]
I was mostly thinking of this line:

https://github.com/ctmrbio/BACTpipe/blame/master/docs/source/running.rst#L40

> When running BACTpipe, you will most likely have to modify the paths for some parameters so that BACTpipe can find reference databases etc.

As far as I know, this line is a remnant from the old version that required a mash screen database path. What do you think? Just want to minimize the risk for confusion for new people reading the docs.
