### ISSUE TITLE
SHOVILL process running with default threads 8

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#149]
It looks like the SHOVILL process doesn't adjust the number of threads according to its environment. It appears to be running with the default settings (i.e. 8 threads) all the time. 

https://github.com/ctmrbio/BACTpipe/blob/master/modules/shovill/shovill.nf#L15-L21

We should add `--cpus ${task.cpus}` to the call to shovill to ensure it optimally uses the resources provided to the process in the different profiles.  https://github.com/tseemann/shovill#advanced-options

@emilio-r  or @abhi18av  could you please get that in there and validate?

**Comment by abhi18av** [comment]
Good catch @boulund !

I've fixed this in https://github.com/ctmrbio/BACTpipe/pull/150
