### ISSUE TITLE
Transfer bactpipe repository to CTMR github organization?

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#15]
I propose we transfer ownership of the `bactpipe_nextflow` repository to the CTMR github organization when it reaches usable maturity. I also propose we change the repository name to just `bactpipe` when transferred to the CTMR organization. 

It won't change anything for access of ease-of-use for us as developers, but it keeps it nicely under the CTMR organization umbrella. After such a transfer, it is still possible for all involved authors to fork the new main repository into their personal github accounts. This also improves the development workflow, as it enables individual researchers to develop code improvements in their local forks, which can the be transferred to the main repo via pull requests. This has the added benefit of making it easier for all involved parties to review all incoming changes. 

Think about it, so we can discuss at a later time.

**Comment by thorellk** [comment]
It think this is a good idea. Should we do it already now or do you want to wait until some later stage @boulund?

**Comment by boulund** [comment]
Whenever really. But if I get to be picky I'd like there to be a LICENSE file and some more in-depth documentation in the repository before transferring.

**Comment by thorellk** [comment]
Added MIT license to the repository

**Comment by b16joski** [comment]
Transferred to ctmrbio
