### ISSUE TITLE
shovill.log output as standard

### ISSUE THREAD

**Issue by emilio-r** [ctmrbio/BACTpipe#152]
I suggest that we again make the Shovill output file `shovill.log` into standard output. It contains very valuable information about the assemblies and just a relatively small text file, making the storage-use rather small in comparison to the usefulness of this file.

**Comment by boulund** [comment]
I think this is a great suggestion! Make a PR!

**Comment by emilio-r** [comment]
@abhi18av, might I trouble you to implement this change at some point? I feel that I'm too unfamiliar with the structure of BACTpipe as it looks now, and would need to take too much time to get accustomed to it again before I would feel comfortable changing something like this.

**Comment by boulund** [comment]
I could point you to where the change needs to be made:

https://github.com/ctmrbio/BACTpipe/blob/master/modules/shovill/shovill.nf#L4

**Comment by emilio-r** [comment]
Thank you for the assistance @boulund! I have now made the change, tested it, and made a pull request here #154.

**Comment by boulund** [comment]
Nice work! Impressive that you made it so quickly! Glad to hear it worked well in testing.

**Comment by boulund** [comment]
Merged to develop 👍
