### ISSUE TITLE
Changelog 3.1

### ISSUE THREAD

**Issue by emilio-r** [ctmrbio/BACTpipe#166]
Updated changelog for the upcoming 3.1 (#160) release, is there anything I'm forgetting or should rephrase?

### Added
- New profile for use on CTMR Gandalf, `ctmr_gandalf`.
- Taxonomic assessment of input reads by `Kraken2`. 
- BACTpipe now supports building with `Docker`images.

### Changed
- Renamed profile for CTMR-NAS to `ctmr_nas` to better conform to incoming
  profiles.
- Moved contig renaming script to shovill process from contamination screen
  process.
- Now publishes `shovill.log` in the output directory by default.
- Limited the search scope for MultiQC to minimize risk of process timeouts on
  HPC systems.
- Taxonomic screening made into an optional module. If a user wishes to make use of this, they must download a relevant `Kraken2` database and specify its location with `--kraken2_db`.

### Removed
- Removed contamination screening of assembled contigs by `SendSketch`.

**Comment by emilio-r** [comment]
I see that I was just a few moments too late with this @boulund  👍

**Comment by boulund** [comment]
Your text is better though! Seems we mentioned exactly the same things anyway :)
