### ISSUE TITLE
Containerization using Docker

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#47]
# Background
Containerization is a technique to make it easier for end users to run stuff without having to install a lot of complicated dependencies. Common tools for this task are [Docker](www.docker.com) and [Singularity](http://singularity.lbl.gov/index.html). Using containers is also very convenient when running on distributed cluster resources, as the container is a complete package containing all of the dependencies (libraries, scripts, tools, etc) required to run the different pipeline steps. 

For our case with BACTpipe, containerization would mean that users only need to have Docker and Nextflow installed in their environment in order to run all of BACTpipe, without having to mess with installing any of the tools used inside the BACTpipe workflow (in theory, users would even be able to run BACTpipe on a Windows machine without too much trouble). Nextflow comes with Docker support out of the box, and it is very easy to use. 

# Containerization of BACTpipe 
A simple approach to containerization of BACTpipe would be to just create a single container (e.g. a Docker image) that contains a miniature Linux environment with all of the tools used by BACTpipe. As Nextflow has built-in support, it is really quite easy to make a BACTpipe container and make Nextflow use that when executing the different processes in the BACTpipe workflow. 

I already made an [image for BACTpipe version 2.2-dev](https://hub.docker.com/r/boulund/bactpipe/) that works just fine. I recently pushed a new branch, `docker_test`, that makes some tiny changes to the Nextflow configuration to make it run the workflow processes inside Docker containers based on the Docker image I made. Nextflow still runs on your machine, but all the processes inside the workflow run inside instances of the Docker container. 

# Improvements
Despite it working very well for now, there are still some improvements to be made:

* Reducing Docker image size. Unfortunately, all of the tools used in BACTpipe have **lots** of dependencies, which creates a rather big Docker image. By carefully removing unnecessary components in the container, or construct a more lean image, the size can be reduced.
* Developing a Singularity container as well, to cater for different users' needs (Singularity is quite popular at C3SE in Gothenburg for example). 
* Documentation for how to use BACTpipe with and without containers will be needed, to make it easy for users to understand what's going on.

**Comment by abhi18av** [comment]
This is related to https://github.com/ctmrbio/BACTpipe/issues/126

**Comment by abhi18av** [comment]
Since we're mostly relying on vanilla conda packages (apart from the prokka one), I think we could re-use the same pattern from here https://github.com/seqeralabs/gatk4-germline-snps-indels/tree/master/containers 

However, the question is where are we going to host these containers. Here are some options

1. Dockerhub / Quay.io (preferred)
2. Personal user repo / Institutional repo


For our own purposes we could rely upon a private docker image for `prokka + signalp` and add the instructions for other pipeline users  on how they can request `signalP` and build the image for themselves.

@boulund @thorellk  @emilio-r  What are your thoughts about this?

**Comment by boulund** [comment]
I think that sounds great, and is how we've built it for other pipelines at CTMR. I have no preference with regards to dockerhub/quay.io, so whatever you think is most convenient is good to me!

I think we should prepare a docker image _without_ signalP as the default for most users, but still add instructions for users so they can build their own image with signalP if they want to. We should definitely build an image for ourselves with signalP 👍

**Comment by emilio-r** [comment]
The only input I have on this is that we are not allowed to use Docker on our HPC due to "security concerns". We have been able/permitted to install and run programs via other containers, such as Singularity, however.

**Comment by boulund** [comment]
It should be straightforward to run a Nextflow workflow with Singularity using Docker images as sources for the singularity images (Singularity can seamlessly use Docker images).

**Comment by abhi18av** [comment]
Cool, then I have a request for you @boulund and @thorellk  , could either one of you please create a separate quay.io repository for each process used in `BACTpipe` and add my user ID as a collaborator please?
https://quay.io/user/abhi18av/


I'd build these containers, test and then push to tese repos.

**Comment by boulund** [comment]
I created a quay.io organization for ctmrbio, and added you as a collaborator @abhi18av . Feel free to start setting things up, I think you should have all the permissions you need to start configuring things for BACTpipe. 

@thorellk @emilio-r  if you create accounts on quay.io I can add you as well.

**Comment by thorellk** [comment]
I have the user name thorellk there as well @boulund :)

**Comment by abhi18av** [comment]
Update:

We're good to go ahead with Docker  🐳 

I'll iron out a few details soon and then request the PR to be taken for a spin on HPC .

![image](https://user-images.githubusercontent.com/12799326/108792976-83230d00-75a8-11eb-929b-f555272098d7.png)


![image](https://user-images.githubusercontent.com/12799326/108792933-6be41f80-75a8-11eb-8ad9-05a99da92523.png)

**Comment by boulund** [comment]
Very nice!

**Comment by abhi18av** [comment]
Yup, this one can be closed :)
