### ISSUE TITLE
Make Nextflow exit if subprocess fail

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#78]
We should put the following line in `nextflow.config`, so we don't have to do all the `&& \`-chaining inside processes, e.g. in https://github.com/ctmrbio/BACTpipe/blob/master/bactpipe.nf#L111 or https://github.com/ctmrbio/BACTpipe/blob/master/bactpipe.nf#L111.
```
// Capture exit codes from upstream processes when piping
process.shell = ['/bin/bash', '-euo', 'pipefail']
```

**Comment by thorellk** [comment]
Is this still actual @boulund?

**Comment by boulund** [comment]
Not sure really... It seems it is not relevant anymore, considering we've stopped chaining like that in the process definitions and things work well anyway. This has been tested a lot in the `screen_for_contaminants` module :D
