### ISSUE TITLE
IslandPath in BACTpipe?

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#82]
I was thinking it could be cool to automatically run IslandPath as part of BACTpipe. Recently saw a self-contained Docker image for it that we could use: https://hub.docker.com/r/brinkmanlab/islandpath/

**Comment by thorellk** [comment]
I think this is a good idea. So the prokka gbk file goes into islandpath

**Comment by thorellk** [comment]
I haven't actually gotten IslanPath to work. Trying to get the docker image results in
```
docker pull brinkmanlab/islandpath
Using default tag: latest
Error response from daemon: manifest for brinkmanlab/islandpath:latest not found
```

**Comment by boulund** [comment]
What did you think of the output from IslandPath @thorellk? I got the impression the output is a bit underwhelming, so is it worth looking into or should we close this issue?

**Comment by thorellk** [comment]
I think it adds very little useful information dissapointingly, I sent them a question about this and got the reply that they were planning to develop it but that it was not in the pipeline atm... So I say yes, close.
