### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#87]
I think it's time we review the workflow components and update the code to run the most recent version of all programs. For example, Shovill has been updated from the previous 0.9.0 version, which removes a lot of annoying dependencies, potentially simplifying the use of BACTpipe.

**Comment by boulund** [comment]
Now that there is an "official" [shovill Docker image](https://github.com/bioboxes/shovill/blob/master/Dockerfile), referred to by Torsten himself, I'm thinking we could reconsider the possibility of dockerizing BACTpipe to simplify the usage. Regardless, we should definitely move to the most recent version to eliminate all the frustrating dependencies the older versions suffered from.

**Comment by thorellk** [comment]
We should definitely update to the latest shovill version. I will ask uppmax to install it.

**Comment by thorellk** [comment]
The shovill version at uppmax is 1.0.0 and the latest is 1.0.1. The differences between the two seems to be really minor so I don't think we need to make any changes. However, we should probably change the installation instructions for shovill in our documentation.

**Comment by boulund** [comment]
Great, thanks for checking! We should update the docs with recommended versions of all tools (I noticed there wasn't anything at the moment).

**Comment by thorellk** [comment]
@boulund I just noted the same

**Comment by thorellk** [comment]
This should be implemented by letting conda handle the dependency installation in v. 3.0
