### ISSUE TITLE
Output contig graph from assembly

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#93]
Another of the more interesting outputs from the assembly is in my opinion the contig graph. Shovill outputs the graph as `contigs.gfa` in the output directory. We could consider publishing this file directly in `BACTpipe_results/shovill`, so users (i.e. me) don't have to go get them from the assembly subdirectories. We could add some "tips" to the docs about how to look at and interpret the results, e.g. using [Bandage](https://rrwick.github.io/Bandage/) to visualize the assembly graph.

**Comment by thorellk** [comment]
In optional shovill output folder in v. 3.0
