### ISSUE TITLE
ConFindr

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#95]
> ConFindr is a pipeline that can detect contamination in bacterial NGS data, both between and within species. It can do this with exceptional sensitivity - two samples mixed together with as few as 500 SNPs between them (> 99.9 percent identity!) can be identified. This allows for stringent quality control of NGS samples.

Maybe this could be interesting for BACTpipe? 

https://lowandrew.github.io/ConFindr/

**Comment by abhi18av** [comment]
It seems that this repo doesn't exists anymore?

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/12799326/100983208-0404d680-356f-11eb-91cb-9a45983b13cb.png">


I searched on the author's repos as well.

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/12799326/100983185-fc453200-356e-11eb-91c0-d1eff5244799.png">

**Comment by boulund** [comment]
It seems to have moved to https://github.com/OLC-Bioinformatics/ConFindr

Not sure it's relevant for us anymore though.
