### ISSUE TITLE
ProphET prophage finding, like PHASTER

### ISSUE THREAD

**Issue by boulund** [ctmrbio/BACTpipe#96]
https://github.com/jaumlrc/ProphET

**Comment by thorellk** [comment]
I have downloaded and will test run :)

**Comment by thorellk** [comment]
This partly falls under the same argument as the core genome analysis, right?

**Comment by boulund** [comment]
Hmmm. Perhaps, yes. Although, one could argue that prophage finding is a less complex task and could be seen as part of a general genome annotation. But I'm perfectly fine holding off on this for now.

**Comment by thorellk** [comment]
Yeah, I added the "partly" of that reason, agree that it could be seen as a part of the annotation. Ok, let's leave it for now and see if it is getting actualized in some context :)
